apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
      app: {{ .Release.Name }}
  name: {{ .Release.Name }}-s3data2
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4096Mi