apiVersion: batch/v1
kind: CronJob
metadata:
  name: deployment-restart-alienvault
  namespace: {{ .Release.Namespace }}
spec:
  concurrencyPolicy: Forbid
  schedule: '0 * * * *' # cron spec of time, here, 8 o'clock
  jobTemplate:
    spec:
      backoffLimit: 5
      activeDeadlineSeconds: 600 
      template:
        spec:
          serviceAccountName: {{ .Release.Name }}-restart-act 
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl 
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/{{ .Release.Name }}-connector-alienvault'
