{{ if .Values.CONNECTOR_HYBRID_ANALYSIS_ENABLED }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-connector-hybrid-analysis-sandbox
  namespace: {{ .Release.Namespace }}
  labels:
   app: {{ .Release.Name }}-connector-hybrid-analysis-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
     app: {{ .Release.Name }}-connector-hybrid-analysis-sandbox
  strategy: {}
  template:
    metadata:
      labels: 
       app: {{ .Release.Name }}-connector-hybrid-analysis-sandbox
    spec:
      containers:
        - env:    
            - name: HYBRID_ANALYSIS_TOKEN
              value: {{ .Values.CONNECTOR_HYBRID_ANALYSIS_TOKEN | quote }}
            - name: HYBRID_ANALYSIS_ENVIRONMENT_ID
              value: {{ .Values.CONNECTOR_HYBRID_ANALYSIS_ENVIRONMENT_ID | quote }}
            - name: HYBRID_ANALYSIS_MAX_TLP
              value: {{ .Values.CONNECTOR_HYBRID_ANALYSIS_MAX_TLP | quote }}
            - name: CONNECTOR_CONFIDENCE_LEVEL
              value: {{ .Values.CONFIDENCE_LEVEL | quote }}
            - name: CONNECTOR_ID
              value: {{ .Values.CONNECTOR_HYBRID_ANALYSIS_UUID | quote }}
            - name: CONNECTOR_LOG_LEVEL
              value: {{ .Values.LOG_LEVEL }}      
            - name: CONNECTOR_NAME
              value: "Hybrid Analysis (Sandbox Windows 10 64bit)"
            - name: CONNECTOR_SCOPE
              value: "StixFile,Artifact,Url,Domain,X-OpenCTI-Hostname"
            - name: CONNECTOR_TYPE
              value: INTERNAL_ENRICHMENT
            - name: CONNECTOR_AUTO
              value: {{ .Values.CONNECTOR_HYBRID_ANALYSIS_AUTO | quote }}
            - name: OPENCTI_TOKEN
              value: {{ .Values.OPENCTI_TOKEN }}
            - name: OPENCTI_URL
              value: "http://{{ .Release.Name }}-opencti:8080"            
          image: opencti/connector-hybrid-analysis-sandbox:{{ .Chart.AppVersion }}
          name: connector-hybrid-analysis-sandbox
          resources: 
            limits:
              memory: 256Mi
              cpu: "200m"
            requests:
              memory: 56Mi
              cpu: "100m"
      restartPolicy: Always
{{ end }}