apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-connector-export-file-csv
  namespace: {{ .Release.Namespace }}
  labels:
   app: {{ .Release.Name }}-connector-export-file-csv
spec:
  replicas: 1
  selector:
    matchLabels:
     app: {{ .Release.Name }}-connector-export-file-csv
  strategy: {}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-connector-export-file-csv
    spec:
      containers:
        - env:
            - name: CONNECTOR_CONFIDENCE_LEVEL
              value: {{ .Values.CONFIDENCE_LEVEL | quote  }}
            - name: CONNECTOR_ID
              value: {{ .Values.CONNECTOR_EXPORT_FILE_CSV_UUID | quote }}
            - name: CONNECTOR_LOG_LEVEL
              value: {{ .Values.LOG_LEVEL }}
            - name: CONNECTOR_NAME
              value: ExportFileCsv
            - name: CONNECTOR_SCOPE
              value: text/csv
            - name: CONNECTOR_TYPE
              value: INTERNAL_EXPORT_FILE
            - name: OPENCTI_TOKEN
              value: {{ .Values.OPENCTI_TOKEN }}
            - name: OPENCTI_URL
              value: "http://{{ .Release.Name }}-opencti:8080"
          image: opencti/connector-export-file-csv:{{ .Chart.AppVersion }}
          name: connector-export-file-csv
          resources: 
            limits:
              memory: 256Mi
              cpu: "200m"
            requests:
              memory: 56Mi
              cpu: "100m"
      restartPolicy: Always