{{ if .Values.CONNECTOR_ALIENVAULT_ENABLED }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-connector-alienvault
  namespace: {{ .Release.Namespace }}
  labels:
   app: {{ .Release.Name }}-connector-alienvault
spec:
  replicas: 1
  selector:
    matchLabels:
     app: {{ .Release.Name }}-connector-alienvault
  strategy: {}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-connector-alienvault
    spec:
      containers:
        - env:
            - name: CONNECTOR_CONFIDENCE_LEVEL
              value: {{ .Values.CONFIDENCE_LEVEL | quote  }}
            - name: CONNECTOR_ID
              value: {{ .Values.CONNECTOR_ALIENVAULT_CONNECTOR_ID  | quote }}
            - name: CONNECTOR_UPDATE_EXISTING_DATA
              value: {{ .Values.CONNECTOR_ALIENVAULT_CONNECTOR_UPDATE_EXISTING_DATA | quote }}
            - name: CONNECTOR_LOG_LEVEL
              value: {{ .Values.LOG_LEVEL }}
          
            - name: ALIENVAULT_BASE_URL
              value: {{ .Values.CONNECTOR_ALIENVAULT_BASE_URL | quote }}     
            - name: ALIENVAULT_API_KEY
              value: {{ .Values.CONNECTOR_ALIENVAULT_API_KEY | quote }}     
            - name: ALIENVAULT_TLP
              value: {{ .Values.CONNECTOR_ALIENVAULT_TLP | quote }}     
            - name: ALIENVAULT_CREATE_OBSERVABLES
              value: {{ .Values.CONNECTOR_ALIENVAULT_CREATE_OBSERVABLES | quote }}     
            - name: ALIENVAULT_CREATE_INDICATORS
              value: {{ .Values.CONNECTOR_ALIENVAULT_CREATE_INDICATORS | quote }}            
            - name: ALIENVAULT_PULSE_START_TIMESTAMP
              value: {{ .Values.CONNECTOR_ALIENVAULT_PULSE_START_TIMESTAMP | quote }}            
            - name: ALIENVAULT_REPORT_TYPE
              value: {{ .Values.CONNECTOR_ALIENVAULT_REPORT_TYPE | quote }}
            - name: ALIENVAULT_REPORT_STATUS
              value: {{ .Values.CONNECTOR_ALIENVAULT_REPORT_STATUS | quote }}
            - name: ALIENVAULT_GUESS_MALWARE
              value: {{ .Values.CONNECTOR_ALIENVAULT_GUESS_MALWARE | quote }}
            - name: ALIENVAULT_GUESS_CVE
              value: {{ .Values.CONNECTOR_ALIENVAULT_GUESS_CVE | quote }}
            - name: ALIENVAULT_EXCLUDED_PULSE_INDICATOR_TYPES
              value: {{ .Values.CONNECTOR_ALIENVAULT_EXCLUDED_PULSE_INDICATOR_TYPES | quote }}
            - name: ALIENVAULT_ENABLE_RELATIONSHIPS
              value: {{ .Values.CONNECTOR_ALIENVAULT_ENABLE_RELATIONSHIPS | quote }}
            - name: ALIENVAULT_ENABLE_ATTACK_PATTERNS_INDICATES
              value: {{ .Values.CONNECTOR_ALIENVAULT_ENABLE_ATTACK_PATTERNS_INDICATES | quote }}
            - name: ALIENVAULT_INTERVAL_SEC
              value: {{ .Values.CONNECTOR_ALIENVAULT_INTERVAL_SEC | quote }}
            - name: CONNECTOR_NAME
              value: "AlienVault"
            - name: CONNECTOR_SCOPE
              value: "alienvault"
            - name: CONNECTOR_TYPE
              value: EXTERNAL_IMPORT
            - name: OPENCTI_TOKEN
              value: {{ .Values.OPENCTI_TOKEN }}
            - name: OPENCTI_URL
              value: "http://{{ .Release.Name }}-opencti:8080"
          image: opencti/connector-alienvault:{{ .Chart.AppVersion }}
          name: connector-alienvault
          resources: {}
      restartPolicy: Always
{{ end }}