apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-connector-history
  namespace: {{ .Release.Namespace }}
  labels:
   app: {{ .Release.Name }}-connector-history
spec:
  replicas: 1
  selector:
    matchLabels:
     app: {{ .Release.Name }}-connector-history
  strategy: {}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-connector-history
    spec:
      containers:
        - env:
            - name: CONNECTOR_CONFIDENCE_LEVEL
              value: {{ .Values.CONFIDENCE_LEVEL | quote  }}
            - name: CONNECTOR_ID
              value: {{ .Values.CONNECTOR_CONNECTOR_HISTORY_UUID |quote }}
            - name: CONNECTOR_LOG_LEVEL
              value: {{ .Values.LOG_LEVEL | quote  }}
            - name: CONNECTOR_NAME
              value: History
            - name: CONNECTOR_SCOPE
              value: history
            - name: CONNECTOR_TYPE
              value: STREAM
            - name: OPENCTI_TOKEN
              value: {{ .Values.OPENCTI_TOKEN | quote  }}
            - name: OPENCTI_URL
              value: "http://{{ .Release.Name }}-opencti:8080"
          image: opencti/connector-history:{{ .Chart.AppVersion }}
          name: connector-history
          resources: 
            limits:
              memory: 256Mi
              cpu: "200m"
            requests:
              memory: 56Mi
              cpu: "100m"
      restartPolicy: Always