{{ if .Values.CONNECTOR_OPENCTI_ENABLED }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-connector-opencti-web
  namespace: {{ .Release.Namespace }}
  labels:
   app: {{ .Release.Name }}-connector-opencti-web
spec:
  replicas: 1
  selector:
    matchLabels:
     app: {{ .Release.Name }}-connector-opencti-web
  strategy: {}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-connector-opencti-web
    spec:
      containers:
        - env:
            - name: CONNECTOR_CONFIDENCE_LEVEL
              value: {{ .Values.CONFIDENCE_LEVEL | quote  }}
            - name: CONNECTOR_ID
              value: {{ .Values.CONNECTOR_OPENCTI_UUID | quote }}
            - name: CONNECTOR_UPDATE_EXISTING_DATA
              value: {{ .Values.CONNECTOR_OPENCTI_CONNECTOR_UPDATE_EXISTING_DATA | quote }}
            - name: CONNECTOR_LOG_LEVEL
              value: {{ .Values.LOG_LEVEL }}
            - name: CONFIG_SECTORS_FILE_URL
              value: {{ .Values.CONNECTOR_OPENCTI_CONFIG_SECTORS_FILE_URL | quote }}
            - name: CONFIG_GEOGRAPHY_FILE_URL
              value: {{ .Values.CONNECTOR_OPENCTI_CONFIG_GEOGRAPHY_FILE_URL | quote }}
            - name: CONFIG_INTERVAL
              value: {{ .Values.CONNECTOR_OPENCTI_INTERVAL | quote }}            
            - name: CONNECTOR_NAME
              value: "OpenCTI"
            - name: CONNECTOR_SCOPE
              value: "marking-definition,identity,location"
            - name: CONNECTOR_TYPE
              value: EXTERNAL_IMPORT
            - name: OPENCTI_TOKEN
              value: {{ .Values.OPENCTI_TOKEN }}
            - name: OPENCTI_URL
              value: "http://{{ .Release.Name }}-opencti:8080"
          image: opencti/connector-opencti:{{ .Chart.AppVersion }}
          name: connector-opencti
          resources: 
            limits:
              memory: 256Mi
              cpu: "200m"
            requests:
              memory: 56Mi
              cpu: "100m"
      restartPolicy: Always
{{ end }}