
{{ if .Values.CONNECTOR_CAPE_ENABLED }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-connector-cape
  namespace: {{ .Release.Namespace }}
  labels:
   app: {{ .Release.Name }}-connector-cape
spec:
  replicas: 1
  selector:
    matchLabels:
     app: {{ .Release.Name }}-connector-cape
  strategy: {}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-connector-cape
    spec:
      containers:
        - env:
            - name: CAPE_START_TASK_ID
              value: {{ .Values.CONNECTOR_CAPE_START_TASK_ID | quote }} 
            - name: CAPE_REPORT_SCORE
              value: {{ .Values.CONNECTOR_CAPE_REPORT_SCORE | quote }}     
            - name: CAPE_CREATE_INDICATORS
              value: {{ .Values.CONNECTOR_CAPE_CREATE_INDICATORS | quote }}     
            - name: CAPE_ENABLE_NETWORK_TRAFFIC
              value: {{ .Values.CONNECTOR_CAPE_ENABLE_NETWORK_TRAFFIC | quote }}     
            - name: CAPE_ENABLE_REGISTRY_KEYS
              value: {{ .Values.CONNECTOR_CAPE_ENABLE_REGISTRY_KEYS | quote }}      
            - name: CAPE_API_URL
              value: {{ .Values.CONNECTOR_CAPE_API_URL | quote }} 
            - name: CAPE_BASE_URL
              value: {{ .Values.CONNECTOR_CAPE_BASE_URL | quote }}     
            - name: CAPE_INTERVAL
              value: {{ .Values.CONNECTOR_CAPE_INTERVAL | quote }}
            - name: VERIFY_SSL
              value: {{ .Values.CONNECTOR_CAPE_VERIFY_SSL | quote }}    
            - name: CONNECTOR_CONFIDENCE_LEVEL
              value: {{ .Values.CONFIDENCE_LEVEL | quote  }}
            - name: CONNECTOR_ID
              value: {{ .Values.CONNECTOR_CAPE_UUID | quote }}
            - name: CONNECTOR_UPDATE_EXISTING_DATA
              value: {{ .Values.CONNECTOR_CAPE_UPDATE_EXISTING_DATA | quote }}
            - name: CONNECTOR_LOG_LEVEL
              value: {{ .Values.LOG_LEVEL }}      
            - name: CONNECTOR_NAME
              value: "Cape Sandbox"
            - name: CONNECTOR_TYPE
              value: EXTERNAL_IMPORT
            - name: OPENCTI_TOKEN
              value: {{ .Values.OPENCTI_TOKEN }}
            - name: OPENCTI_URL
              value: "http://{{ .Release.Name }}-opencti:8080"
          image: 91ab06f14e/connector-cape:latest #opencti/connector-cape:{{ .Chart.AppVersion }}
          name: connector-cape
          resources: 
            limits:
              memory: 4096Mi
              cpu: "500m"
            requests:
              memory: 2096Mi
              cpu: "100m"
      restartPolicy: Always
{{ end }}