{{ if .Values.CONNECTOR_INTEZER_ENABLED }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-connector-riskiq
  namespace: {{ .Release.Namespace }}
  labels:
   app: {{ .Release.Name }}-connector-riskiq
spec:
  replicas: 1
  selector:
    matchLabels:
     app: {{ .Release.Name }}-connector-riskiq
  strategy: {}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-connector-riskiq
    spec:
      containers:
        - env:    
            - name: RISKIQ_BASE_URL
              value: {{ .Values.CONNECTOR_RISKIQ_BASE_URL| quote }}
            - name: RISKIQ_USER
              value: {{ .Values.CONNECTOR_RISKIQ_USER | quote }}
            - name: RISKIQ_PASSWORD
              value: {{ .Values.CONNECTOR_RISKIQ_PASSWORD | quote }}
            - name: RISKIQ_INTERVAL_SEC
              value: {{ .Values.CONNECTOR_RISKIQ_INTERVAL_SEC | quote }}
            - name: CONNECTOR_CONFIDENCE_LEVEL
              value: {{ .Values.CONFIDENCE_LEVEL | quote }}
            - name: CONNECTOR_ID
              value: {{ .Values.CONNECTOR_RISKIQ_UUID | quote }}
            - name: CONNECTOR_LOG_LEVEL
              value: {{ .Values.CONNECTOR_RISKIQ_LOG_LEVEL }}      
            - name: CONNECTOR_NAME
              value: "RISKIQ"
            - name: CONNECTOR_SCOPE
              value: "riskiq"
            - name: CONNECTOR_TYPE
              value: EXTERNAL_IMPORT
            - name: CONNECTOR_AUTO
              value:  {{ .Values.CONNECTOR_INTEZER_AUTO | quote }}
            - name: OPENCTI_TOKEN
              value: {{ .Values.OPENCTI_TOKEN }}
            - name: OPENCTI_URL
              value: "http://{{ .Release.Name }}-opencti:8080"            
          image: opencti/connector-riskiq:{{ .Chart.AppVersion }}
          name: connector-riskiq
          resources: 
            limits:
              memory: 256Mi
              cpu: "200m"
            requests:
              memory: 56Mi
              cpu: "100m"
      restartPolicy: Always
{{ end }}