{{ if .Values.CONNECTOR_MITRE_ENABLED }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-connector-mitre
  namespace: {{ .Release.Namespace }}
  labels:
   app: {{ .Release.Name }}-connector-mitre
spec:
  replicas: 1
  selector:
    matchLabels:
     app: {{ .Release.Name }}-connector-mitre
  strategy: {}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-connector-mitre
    spec:
      containers:
        - env:
            - name: MITRE_ENTERPRISE_FILE_URL
              value: {{ .Values.CONNECTOR_MITRE_ENTERPRISE_FILE_URL | quote }}     
            - name: MITRE_PRE_ATTACK_FILE_URL
              value: {{ .Values.CONNECTOR_MITRE_PRE_ATTACK_FILE_URL | quote }}     
            - name: MITRE_MOBILE_ATTACK_FILE_URL
              value: {{ .Values.CONNECTOR_MITRE_MOBILE_ATTACK_FILE_URL | quote }}     
            - name: CONNECTOR_MITRE_INTERVAL
              value: {{ .Values.CONNECTOR_MITRE_INTERVAL | quote }}    
            - name: CONNECTOR_CONFIDENCE_LEVEL
              value: {{ .Values.CONFIDENCE_LEVEL | quote  }}
            - name: CONNECTOR_ID
              value: {{ uuidv4 }}
            - name: CONNECTOR_UPDATE_EXISTING_DATA
              value: {{ .Values.CONNECTOR_MITRE_CONNECTOR_UPDATE_EXISTING_DATA | quote }}
            - name: CONNECTOR_LOG_LEVEL
              value: {{ .Values.LOG_LEVEL }}      
            - name: CONNECTOR_NAME
              value: "MITRE ATT&CK"
            - name: CONNECTOR_SCOPE
              value: "marking-definition,identity,attack-pattern,course-of-action,intrusion-set,campaign,malware,tool,report,external-reference-as-report"
            - name: CONNECTOR_TYPE
              value: EXTERNAL_IMPORT
            - name: OPENCTI_TOKEN
              value: {{ .Values.OPENCTI_TOKEN }}
            - name: OPENCTI_URL
              value: "http://{{ .Release.Name }}-opencti:8080"
          image: opencti/connector-mitre:{{ .Chart.AppVersion }}
          name: connector-mitre
          resources: {}
      restartPolicy: Always
{{ end }}