apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-connector-import-file-stix
  namespace: {{ .Release.Namespace }}
  labels:
   app: {{ .Release.Name }}-connector-import-file-stix
spec:
  replicas: 1
  selector:
    matchLabels:
     app: {{ .Release.Name }}-connector-import-file-stix
  strategy: {}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-connector-import-file-stix
    spec:
      containers:
        - env:
            - name: CONNECTOR_CONFIDENCE_LEVEL
              value: {{ .Values.CONFIDENCE_LEVEL | quote  }}
            - name: CONNECTOR_ID
              value: {{ uuidv4 }}
            - name: CONNECTOR_LOG_LEVEL
              value: {{ .Values.LOG_LEVEL | quote  }}
            - name: CONNECTOR_NAME
              value: ImportFileStix
            - name: CONNECTOR_SCOPE
              value: application/json,text/xml
            - name: CONNECTOR_TYPE
              value: INTERNAL_IMPORT_FILE
            - name: OPENCTI_TOKEN
              value: {{ .Values.OPENCTI_TOKEN | quote }}
            - name: OPENCTI_URL
              value: "http://{{ .Release.Name }}-opencti:8080"
          image: opencti/connector-import-file-stix:{{ .Chart.AppVersion }}
          name: connector-import-file-stix
          resources: {}
      restartPolicy: Always