{{ if .Values.CONNECTOR_SHODAN_ENABLED }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-connector-shodan
  namespace: {{ .Release.Namespace }}
  labels:
   app: {{ .Release.Name }}-connector-shodan
spec:
  replicas: 1
  selector:
    matchLabels:
     app: {{ .Release.Name }}-connector-shodan
  strategy: {}
  template:
    metadata:
      labels:
       app: {{ .Release.Name }}-connector-shodan
    spec:
      containers:
        - env:    
            - name: SHODAN_TOKEN
              value: {{ .Values.CONNECTOR_SHODAN_TOKEN| quote }}
            - name: SHODAN_MAX_TLP
              value: {{ .Values.CONNECTOR_SHODAN_MAX_TLP | quote }}
            - name: CONNECTOR_CONFIDENCE_LEVEL
              value: {{ .Values.CONFIDENCE_LEVEL | quote }}
            - name: CONNECTOR_ID
              value: {{ .Values.CONNECTOR_SHODAN_UUID | quote }}
            - name: CONNECTOR_LOG_LEVEL
              value: {{ .Values.LOG_LEVEL }}      
            - name: CONNECTOR_NAME
              value: "Shodan"
            - name: CONNECTOR_SCOPE
              value: "IPv4-Addr"
            - name: CONNECTOR_TYPE
              value: INTERNAL_ENRICHMENT
            - name: CONNECTOR_AUTO
              value:  {{ .Values.CONNECTOR_SHODAN_AUTO | quote }}
            - name: OPENCTI_TOKEN
              value: {{ .Values.OPENCTI_TOKEN }}
            - name: OPENCTI_URL
              value: "http://{{ .Release.Name }}-opencti:8080"            
          image: opencti/connector-shodan:latest
          name: connector-shodan
          resources: 
            limits:
              memory: 256Mi
              cpu: "200m"
            requests:
              memory: 56Mi
              cpu: "100m"
      restartPolicy: Always
{{ end }}