apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio
  namespace: {{ .Release.Namespace }}
  labels:
      app: {{ .Release.Name }}-minio
spec:
  ports:
    - name: "minio"
      port: 9000
      targetPort: 9000
  selector:
      app: {{ .Release.Name }}-minio
status:
  loadBalancer: {}