apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-opencti-web
  namespace: {{ .Release.Namespace }}
  labels:
      app: {{ .Release.Name }}-opencti-web
spec:
  ports:
    - name: "opencti"
      port: 8080
      targetPort: 8080
  selector:
      app: {{ .Release.Name }}-opencti-web
status:
    loadBalancer: {}