apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rabbitmq
  namespace: {{ .Release.Namespace }}
  labels:
      app: {{ .Release.Name }}-rabbitmq
spec:
  ports:
  - name: "rabbitmq"
    port: 5672
    targetPort: 5672
  - name: "rabbitmq-mgmt"
    port: 15672
    targetPort: 15672
  selector:
      app: {{ .Release.Name }}-rabbitmq
status:
    loadBalancer: {}